### ISSUE TITLE
Google drive links inaccessible/invalid for examples/simple_example

### ISSUE THREAD

**Issue by winch-jm** [royerlab/cytoself#12]
Hello,

I have set-up a conda environment according to the instructions in the README and I receive the following message in my terminal when I run `python examples/simple_example.py`:

```(cytoself) usr@usrpc:~/Desktop/cytoself$ python examples/simple_example.py 
Downloading data...
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1gkiEMKdadOel4Xh6KoS2U603JTkZhgDw 

Downloading...
From: https://drive.google.com/uc?id=16-0bhKrUMbZ0DSz768Z_q13yNivHyfVO
To: /my/computer/Desktop/cytoself/example_label.npy
100%|████████████████████████████████████████████████████████████████| 51.3k/51.3k [00:00<00:00, 15.8MB/s]
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1znRLbYJJqd11Zqv-5_yUmNjarKcwIWMg 

Downloading...
From: https://drive.google.com/uc?id=1RM654Qavcy8gG5uy3mCzi8EsOT_xOlVd
To: /my/computer/Desktop/cytoself/protein_uniloc.csv
100%|████████████████████████████████████████████████████████████████| 8.57k/8.57k [00:00<00:00, 28.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1WrxhGsSzivZVAlL_K2FLVsRmHrsfhyrI
To: /my/computer/Desktop/cytoself/dgram_index1.npy
100%|████████████████████████████████████████████████████████████████| 16.5k/16.5k [00:00<00:00, 21.7MB/s]
Loading data...
Traceback (most recent call last):
  File "examples/simple_example.py", line 49, in <module>
    image_data = np.load('example_image.npy')
  File "/my/computer/anaconda3/envs/cytoself/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'example_image.npy'
```
When I try the google drive links in-browser (as suggested) they lead to files with different names. Any tips on how to resolve this?

Thanks,
Jeff

**Comment by li-li-github** [comment]
Hi, sorry for the belated reply. I recently upgraded cytoself-pytorch branch to the main branch. The data downloading is now embedded inside `DataManagerOpenCell.download_sample_data` and as far as I tested, there was no problem. 
What you tried was the old tensorflow implementation and some of the download link might have broken.

**Comment by winch-jm** [comment]
Hi, thanks for the reply! I confirmed that the pytorch version runs and will use that instead.
